### ISSUE TITLE
Tracking issue for stable Rust

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/canvas#1]
The only blocking issue for compiling this on stable Rust seems to be the dependency `zerocopy`. It requires an unstable feature to provide interpreting `RefCell` derived `Ref` and `RefMut` as byte buffers that is not used here.

@joshlf who advertised the library originally in https://github.com/image-rs/image/pull/885 , I suppose this could also be relevant as user experience. There are a few other utils that required additional implementation and might be useful in `zerocopy` in general, if you find them interesting. Since I don't know where else to submit these issues, we can potentially discuss them here, on gitter or any other place? The two methods are:

* `align_to`: Just like [`[T]::align_to`](https://doc.rust-lang.org/std/primitive.slice.html#method.align_to) but safe. Note that a better implementation could require [`ptr::align_offset`](https://doc.rust-lang.org/std/primitive.pointer.html#method.align_offset) which is not yet stable. https://github.com/image-rs/canvas/blob/0c591e0d6aca8bb19c3850a1e0dee435db614d28/src/buf.rs#L93-L111
* `prefix_slice`: Just like the single element methods but for a slice layout. https://github.com/image-rs/canvas/blob/0c591e0d6aca8bb19c3850a1e0dee435db614d28/src/buf.rs#L113-L118

**Comment by joshlf** [comment]
> It requires an unstable feature to provide interpreting `RefCell` derived `Ref` and `RefMut` as byte buffers that is not used here.

That's been stabilized in nightly, and will be stabilized in stable as soon as the next stable release lands.

> There are a few other utils that required additional implementation and might be useful in `zerocopy` in general, if you find them interesting. Since I don't know where else to submit these issues, we can potentially discuss them here, on gitter or any other place?

That's very useful, thanks! Yeah, discussing them here is fine; unfortunately Fuchsia doesn't have a public bug tracker yet, which makes these sorts of things difficult.

**Comment by joshlf** [comment]
`align_to` sounds totally feasible. I'd be happy to add it. I'm not sure I understand `prefix_slice`, though. It doesn't seem to use any unsafe code; is it just a convenience thing?

**Comment by HeroicKatora** [comment]
>  That's been stabilized in nightly, and will be stabilized in stable as soon as the next stable release lands.

Ah, I didn't know that already completed its FCP. Must have missed it in the weekly summary.

Yes, `align_to` is mostly convenience with a pinch of API consistency. There is `new`, which requires and exact size, and `new_from_prefix` which does not but instead gives back the remainder. But for slices there is only `new_slice` but no equivalent to get to pass a block that is not a multiple of the required size. This helper was quite applicable to two rather different places in the code, so I extracted it into a function and figured it could be useful in general.

For `align_to` it could also be useful to have one which only provides `Option<(B, LayoutVerified<T, B>, B)` instead of a verified slice. This would be the case when one wants to manually segment memory for a `repr(C)` struct, I think.

**Comment by HeroicKatora** [comment]
Whoops, messed up the name when responding and referred to `align_to` instead of `prefix_slice`. It should now actually make sense.
