### ISSUE TITLE
A container without static pixel type

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/canvas#15]
The type safety of specifying exact pixel *types* is sometimes nice but *unecessary* and creates extra friction in consumers. A generic buffer for `image::ColorType` should not require providing some particular choice for the pixel type, only when it is accessed by (mutable) borrow does it become important and can be runtime checked.

Also note that many methods can be implemented without knowledge of the type with merely the size of pixels. The same applies to `Layout` which only requires the type to check the result byte length and could do the same with the size of the type only. A non-exhaustive list:

* `copy_from`
* `copy_within`
* `reserve`
* `shrink`
* `shrink_to_fit`
* `memset`/`memzero`/`repeat`
* `resize` (with zeroed semantics)

**Comment by fintelia** [comment]
In my opinion, "a generic buffer for image::ColorType" is almost exactly the role that image::DynamicImage should hold

**Comment by HeroicKatora** [comment]
Most aptly put (and that was part of the eventual goal). But some level of backwards compatibility would be nice. Let's not overlook that the `enum` properties of `DynamicImage` make it more powerful in some cases, and the fact that *this* new type could not possibly implement `GenericImage` in its current form as it has no single associated pixel type.

**Comment by HeroicKatora** [comment]
To put this more precisely, the new type *might* have an interface like this:

```rust
impl Dynamic {
    pub fn get<P: image::Pixel + AsPixel>(&self) -> Option<impl image::GenericImage> { … }
}
```

**Comment by fintelia** [comment]
Right now my thinking is that image should center around 3 types: a DynamicImage type like we've been describing here, a ImageBuffer type that gives statically known color/channel types, and a trait like GenericImage/[ContigiousImage](https://github.com/image-rs/image/issues/1118) that is implemented for both of them (and where all the actual image processing logic lives).

**Comment by HeroicKatora** [comment]
I'm not sure if the trait is the correct public interface. We've already had plenty of examples in `imageproc` where a specialized method for `ImageBuffer` showed better performance but it is currently not possible for an external crate to be both generic in `GenericImage` and have a specialized method that extends the trait at the same time.

My main question was why we *relying* on a trait at all? All C libraries for imageprocessing can do without it, so does `numpy`/`Pillow`. We have it at the moment because `subimage` could not be feasible be implemented but the types are different only because `ImageBuffer` *owns* the image and `SubImage` does not. So the radical solution would be to have *no* owning type that is bound to a specific `Pixel` and move all processing to a common type borrowing type (not unlike `flat::ViewMut`).

**Comment by HeroicKatora** [comment]
New PR to address this problem: #17
